<TopBar>

    orientation: "vertical"
    spacing: "12dp"
    pos_hint: {"top": 1}
    adaptive_height: True

    MDTopAppBar:
        type_height: 'medium'
        headline_text: "Rifles /"
        md_bg_color: "#2d2734"
        title: "eBallistica"
        anchor_title: "left"
#            left_action_items: [["menu", lambda x: x]]
#            right_action_items: [["dots-vertical", lambda x: x]]
        right_action_items: [["cog-outline", lambda x: x]]