<RifleListItem>
    text: "New rifle"
#    font_style: "Subtitle1"
    md_bg_color: "#191c1a"
    secondary_text: "Twist: 1 in <num> <units>"
    secondary_font_style: "Caption"
    tertiary_text: "Sight height: <num> <units>"
    tertiary_font_style: "Caption"


<RiflesList>

    MDList:
        id: rifles_list

        RifleListItem:
            md_bg_color: "#191c1a"
        RifleListItem:
        RifleListItem:


<RiflesScreen>:
    name: 'rifles_screen'

    RiflesList: