name: CI android build
on:

  push:
    branches:
      - test-sqlalchemy-support

jobs:
  build_debug:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Download Artifacts
        uses: actions/download-artifact@v2
        with:
          name: buildozer-artifacts   # The name of the uploaded artifacts
          workflow: 5917303319 # Replace with the actual workflow_run ID
          path: .buildozer

      # - name: Setup Android SDK
      #  uses: android-actions/setup-android@v2

      - name: Set up Python 3.10.10
        if: ${{ always() }}
        uses: actions/setup-python@v2
        with:
          python-version: 3.10.10
          
      # Add caching step for Python dependencies
      - name: Cache Python dependencies
        if: ${{ always() }}
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements*.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
          
      - name: Setup environment
        if: ${{ always() }}
        run: |
          sudo apt-get install libtool
          pip install --user --upgrade Cython==0.29.36
          pip install --user --upgrade buildozer
          pip freeze > requirements-pre.txt

      # Install OS specific dependencies
      - name: Install Linux dependencies
        if: ${{ always() }}
        run: sudo apt -y install automake

      # - name: Reinit buildozer.spec
      #   run: |
          # rm buildozer.spec
          # buildozer init
      
      - name: SDK, NDK and p4a download
        if: ${{ always() }}
        run: |
          sed -i.bak "s/# android.accept_sdk_license = False/android.accept_sdk_license = True/" buildozer.spec
          sed -i.bak "s/#p4a.branch = master/p4a.branch = develop/" buildozer.spec
          buildozer android p4a -- --help

      - name: Extract version from main.py
        if: ${{ always() }}
        id: extract_version
        run: |
          version=$(grep -o "__version__ = '[0-9.]*'" main.py | sed "s/__version__ = '//" | sed "s/'//")
          echo "Extracted version: $version"
          echo "::set-output name=version::$version"

      - name: Update buildozer.spec
        if: ${{ always() }}
        run: |
          sed -i.bak "s/version =.*/version = ${{ steps.extract_version.outputs.version }}/" buildozer.spec

#  #      For running on native machine:
#          requirements=$(grep -Eo '[^[:space:]]+' requirements.txt | tr '\n' ',')
#          sed -i.bak "s|requirements =.*|requirements = python3,$requirements|" buildozer.spec
#
#          version=$(grep -o "__version__ = '[0-9.]*'" main.py | sed "s/__version__ = '//" | sed "s/'//")
#          sed -i.bak "s/version =.*/version = $version/" buildozer.spec

      - name: Extract build requirements
        if: ${{ always() }}
        id: update_requirements
        run: |
          requirements=$(grep -Eo '[^[:space:]]+' requirements.txt | tr '\n' ',')
          echo "Extracted requirements: $requirements"
          echo "::set-output name=requirements::$requirements"

      - name: Update buildozer.spec with extracted requirements
        if: ${{ always() }}
        run: |
          sed -i.bak "s|requirements =.*|requirements = python3,${{ steps.update_requirements.outputs.requirements }}|" buildozer.spec

      - name: Upload Artifacts (buildozer.spec)
        if: ${{ always() }}
        uses: actions/upload-artifact@v2
        with:
          name: build-artifacts-spec
          path: buildozer.spec

      - name: buildozer android debug
        if: ${{ always() }}
        run: |
          touch main.py
          buildozer android debug

#      - name: Save buildozer artifacts
#        if: ${{ always() }}  # This condition runs the step even if previous steps fail
#        uses: actions/upload-artifact@v2
#        with:
#          name: buildozer-artifacts
#          path: |
#            .buildozer

# # Temporary removed
#      - name: buildozer android release (aab)
#        run: |
#          touch main.py
#          export BUILDOZER_ALLOW_ORG_TEST_DOMAIN=1
#          buildozer android release

#      - run: pip freeze > requirements.txt
      
#      - name: Upload Artifacts
#        uses: actions/upload-artifact@v2
#        with:
#          name: build-artifacts-debug
#          path: requirements.txt
      
      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: build-artifacts-release
          path: bin

      - name: Upload and Send to Telegram
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TG_USER_ID }}
          token: ${{ secrets.TG_GITHUB_ARTIFACTS_TOKEN }}
          document: ./bin/* # Change the path to match your artifacts
          
