name: TestAndroidBuild
on:
  push:
    branches: [ "autobuild-android" ]
  pull_request:
    branches: [ "autobuild-android" ]
  schedule:
    - cron: '0 0 1,15 * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      # - name: Setup Android SDK
      #  uses: android-actions/setup-android@v2

      - name: Set up Python 3.10.10
        uses: actions/setup-python@v2
        with:
          python-version: 3.10.10
          
      # Add caching step for Python dependencies
      - name: Cache Python dependencies
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements*.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
          
      - name: Setup environment
        run: |
          sudo apt-get install libtool
          pip install --user --upgrade Cython==0.29.36
          pip install --user --upgrade buildozer
          pip freeze > requirements-pre.txt
      
      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: build-artifacts
          path: requirements-pre.txt
          
      # - name: Reinit buildozer.spec
      #   run: |
          # rm buildozer.spec
          # buildozer init
      
      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: build-artifacts
          path: buildozer.spec 
      
      - name: SDK, NDK and p4a download
        run: |
          sed -i.bak "s/# android.accept_sdk_license = False/android.accept_sdk_license = True/" buildozer.spec
          sed -i.bak "s/#p4a.branch = master/p4a.branch = develop/" buildozer.spec
          buildozer android p4a -- --help
      # Install OS specific dependencies
      - name: Install Linux dependencies
        run: sudo apt -y install automake

      - name: buildozer android debug
        run: |
          touch main.py
          buildozer android debug
      - name: buildozer android release (aab)
        run: |
          touch main.py
          export BUILDOZER_ALLOW_ORG_TEST_DOMAIN=1
          buildozer android release

      - run: pip freeze > requirements.txt
      
      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: build-artifacts
          path: requirements.txt
      
      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: build-artifacts
          path: bin
          
